alter table sudokus add SDKS_X_SDK varchar(1) default 'N';
alter table sudokus drop SDKS_X_SDK;
alter table sudokus add SDKS_STRGY_SIMPLE integer;
alter table sudokus drop SDKS_STRGY_SIMPLE;
alter table sudokus add SDKS_STRGY_HIDDEN_SINGLE integer;
alter table sudokus drop SDKS_STRGY_HIDDEN_SINGLE;
alter table sudokus add SDKS_STRGY_NAKED_PAIR integer;
alter table sudokus drop SDKS_STRGY_NAKED_PAIR;
alter table sudokus add SDKS_STRGY_NAKED_TRIPLE integer;
alter table sudokus drop SDKS_STRGY_NAKED_TRIPLE;
alter table sudokus add SDKS_STRGY_NAKED_QUAD integer;
alter table sudokus drop SDKS_STRGY_NAKED_QUAD;
alter table sudokus add SDKS_STRGY_HIDDEN_PAIR integer;
alter table sudokus drop SDKS_STRGY_HIDDEN_PAIR;
alter table sudokus add SDKS_STRGY_HIDDEN_TRIPLE integer;
alter table sudokus drop SDKS_STRGY_HIDDEN_TRIPLE;
alter table sudokus add SDKS_STRGY_HIDDEN_QUAD integer;
alter table sudokus drop SDKS_STRGY_HIDDEN_QUAD;
alter table sudokus add SDKS_STRGY_INTERSECTION_REMOVAL integer;
alter table sudokus drop SDKS_STRGY_INTERSECTION_REMOVAL;
alter table sudokus add SDKS_STRGY_XWING integer;
alter table sudokus drop SDKS_STRGY_XWING;
alter table sudokus add SDKS_STRGY_SWORDFISH integer;
alter table sudokus drop SDKS_STRGY_SWORDFISH;
